CC = gcc

INCLUDES = -I ../part1
CFLAGS = -g -Wall $(INCLUDES)

LDFLAGS = -g -L../part1
LDLIBS =  -lmylist


revecho: revecho.o

revecho.o: revecho.c

.PHONY: clean
clean:
	rm -f *.o a.out core revecho Makefile~ revecho.c~

.PHONY: all
all: clean make
